import type { Event } from './types'

export const event: Event = {
  name: 'UNIHACK Melbourne 2017',
  id: '2017-melbourne',
  type: 'IN_PERSON',
  year: 2017,
  location: 'Monash Business School, Melbourne',
  url: 'https://unihack2017mel.devpost.com/',
  startDate: new Date('2017-08-05'),
  endDate: new Date('2017-08-06'),
  prizesNote: {
    type: 'INFO',
    text: [
      'Some Devpost submissions are incomplete or missing. Some teams may have taken down their submissions.',
      'Between 2015-2019, Devpost was only used to record projects submitted. All judging was done in-person on the final day of the hackathon. As a result, quality of Devpost submissions may vary.',
    ],
  },
  prizes: [
    {
      name: 'First Place',
      winner: 'Resolvr',
      type: 'MAIN',
      place: 'FIRST',
      devpostUrl: 'https://devpost.com/software/resolvr',
    },
    {
      name: 'Second Place',
      winner: 'SeatMe',
      type: 'MAIN',
      place: 'SECOND',
      devpostUrl: 'https://devpost.com/software/seatme',
    },
    {
      name: 'Third Place',
      winner: 'Searchable',
      type: 'MAIN',
      place: 'THIRD',
      devpostUrl: 'https://devpost.com/software/searchable',
    },
    {
      name: 'Complex Challenge Award',
      winner: 'Resolvr',
      type: 'SPONSOR',
      sponsor: 'Optiver',
      devpostUrl: 'https://devpost.com/software/resolvr',
    },
    {
      name: '#Beautiful Award',
      winner: 'Resolvr',
      type: 'SPONSOR',
      sponsor: 'Xero',
      devpostUrl: 'https://devpost.com/software/resolvr',
    },
    {
      name: 'Complex Challenge Award',
      winner: 'Searchable',
      type: 'SPONSOR',
      sponsor: 'Optiver',
      devpostUrl: 'https://devpost.com/software/searchable',
    },
    {
      name: 'Best Mobile Experience',
      winner: 'Crimefeed',
      type: 'SPONSOR',
      sponsor: 'IttyBittyApps',
      devpostUrl: 'https://devpost.com/software/crimefeed',
    },
    {
      name: 'Best Use of Accenture API',
      winner: 'Sweet Dreams are made of Memes',
      type: 'SPONSOR',
      sponsor: 'Accenture',
      devpostUrl: 'https://devpost.com/software/sweet-dreams-are-made-of-memes',
    },
    {
      name: 'Best Industrial IOT Hack',
      winner: 'Waitless',
      type: 'SPONSOR',
      sponsor: 'Bosch',
      devpostUrl: 'https://devpost.com/software/waitless-gknzs7',
    },
    {
      name: 'Best Design',
      winner: 'Crimefeed',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/crimefeed',
    },
    {
      name: 'Most Creative Idea',
      winner: 'Pyrome',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/unihack2017',
    },
  ],
}
