import type { Event } from './types'

export const event: Event = {
  name: 'UNIHACK Melbourne 2018',
  id: '2018-melbourne',
  year: 2018,
  type: 'IN_PERSON',
  location: 'Telstra Labs, Melbourne',
  url: 'https://unihack2018mel.devpost.com/',
  startDate: new Date('2018-07-28'),
  endDate: new Date('2018-07-29'),
  prizesNote: {
    type: 'INFO',
    text: [
      'Some Devpost submissions are incomplete or missing. Some teams may have taken down their submissions.',
      'Between 2015-2019, Devpost was only used to record projects submitted. All judging was done in-person on the final day of the hackathon. As a result, quality of Devpost submissions may vary.',
    ],
  },
  prizes: [
    {
      name: 'First Place',
      winner: 'MEDItrace',
      type: 'MAIN',
      place: 'FIRST',
      devpostUrl: 'https://devpost.com/software/meditrace',
    },
    {
      name: 'Second Place',
      winner: 'DriveAway',
      type: 'MAIN',
      place: 'SECOND',
      devpostUrl: 'https://devpost.com/software/drive-away-sdi5fw',
    },
    {
      name: 'Third Place',
      winner: 'Step By Step',
      type: 'MAIN',
      place: 'THIRD',
      devpostUrl: 'https://devpost.com/software/happyhackers-unihack-2018',
    },
    {
      name: 'Best Potential Startup',
      winner: 'Meta Twitch',
      type: 'SPONSOR',
      sponsor: 'Wade Institute',
      devpostUrl: 'https://devpost.com/software/fantasy-tube',
    },
    {
      name: 'Best Mobile Experience',
      winner: 'Firebendr',
      type: 'SPONSOR',
      sponsor: 'IttyBittyApps',
      devpostUrl: 'https://devpost.com/software/firebendr',
    },
    {
      name: 'From Things to Internet Things Grow Award',
      winner: 'trackr',
      type: 'SPONSOR',
      sponsor: 'Bosch',
      devpostUrl: 'https://devpost.com/software/trackr-8byv9x',
    },
    {
      name: '#Beautiful Award',
      winner: 'FOMO App',
      type: 'SPONSOR',
      sponsor: 'Xero',
      devpostUrl: 'https://devpost.com/software/fomo-app',
    },
    {
      name: 'All Star Award',
      winner: 'FOMO App',
      type: 'SPONSOR',
      sponsor: 'Hacker Exchange',
      devpostUrl: 'https://devpost.com/software/fomo-app',
    },
    {
      name: 'Best Hack on a .tech Domain',
      winner: 'ThingFinder',
      type: 'SPONSOR',
      sponsor: '.tech domains',
      devpostUrl: 'https://devpost.com/software/thingfinder',
    },
    {
      name: 'Best Design',
      winner: 'MEDItrace',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/meditrace',
    },
    {
      name: 'Most Creative Idea',
      winner: 'Low Heat',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/low-heat',
    },
    {
      name: 'Best Pitch',
      winner: 'MEDItrace',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/meditrace',
    },
    {
      name: 'Best IOT/Hardware Hack',
      winner: 'Step By Step',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/happyhackers-unihack-2018',
    },
  ],
}
