import type { Event } from './types'

export const event: Event = {
  name: 'UNIHACK Melbourne 2019',
  year: 2019,
  type: 'IN_PERSON',
  location: 'Telstra Labs, Melbourne',
  url: 'https://unihack2019.devpost.com/',
  startDate: new Date('2019-03-16'),
  endDate: new Date('2019-03-17'),
  prizesNote: {
    type: 'INFO',
    text: [
      'Some Devpost submissions are incomplete or missing. Some teams may have taken down their submissions.',
      'Between 2015-2019, Devpost was only used to record projects submitted. All judging was done in-person on the final day of the hackathon. As a result, quality of Devpost submissions may vary.',
    ],
  },
  prizes: [
    {
      name: 'First Place',
      winner: 'Saturn Space',
      type: 'MAIN',
      place: 'FIRST',
      devpostUrl: 'https://devpost.com/software/saturn-space',
    },
    {
      name: 'Second Place',
      winner: 'Hire Me',
      type: 'MAIN',
      place: 'SECOND',
      devpostUrl: 'https://devpost.com/software/hire-me-30zbpu',
    },
    {
      name: 'Third Place',
      winner: 'iValuate',
      type: 'MAIN',
      place: 'THIRD',
      devpostUrl: 'https://devpost.com/software/practice-interview',
    },
    {
      name: 'Best Startup Potential',
      winner: 'iValuate',
      type: 'SPONSOR',
      sponsor: 'Wade Institute',
      devpostUrl: 'https://devpost.com/software/practice-interview',
    },
    {
      name: '#Beautiful',
      winner: 'Circles',
      type: 'SPONSOR',
      sponsor: 'Xero',
      devpostUrl: 'https://devpost.com/software/circles-mzp7ei',
    },
    {
      name: 'Best IoT Hack',
      winner: 'ReadyTable',
      type: 'SPONSOR',
      sponsor: 'Bosch',
      devpostUrl: 'https://devpost.com/software/readytable-wm3n8i',
    },
    {
      name: 'Best Startup Potential',
      winner: 'ReadyTable',
      type: 'SPONSOR',
      sponsor: 'Wade Institute',
      devpostUrl: 'https://devpost.com/software/readytable-wm3n8i',
    },
    {
      name: 'Open Source, Open Spirit',
      winner: 'Bull Vision',
      type: 'SPONSOR',
      sponsor: 'GitHub',
      devpostUrl: 'https://devpost.com/software/1111111',
    },
    {
      name: '#Community',
      winner: 'prefer.io',
      type: 'SPONSOR',
      sponsor: 'Cognizant',
      devpostUrl: 'https://devpost.com/software/prefer-io',
    },
    {
      name: 'Best Design',
      winner: 'Circles',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/circles-mzp7ei',
    },
    {
      name: 'Most Creative Idea',
      winner: 'AVoice',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/unihack-19-team30',
    },
  ],
}
