import type { Event } from './types'

export const event: Event = {
  name: 'UNIHACK 2021',
  year: 2021,
  type: 'VIRTUAL',
  url: 'https://unihack2021.devpost.com/',
  location: 'Remote',
  startDate: new Date('2021-03-05'),
  endDate: new Date('2021-03-07'),
  prizes: [
    {
      name: 'First Place',
      winner: 'Scalr.io',
      type: 'MAIN',
      place: 'FIRST',
      devpostUrl: 'https://devpost.com/software/scalr-ht4loi',
    },
    {
      name: 'Second Place',
      winner: 'koff',
      type: 'MAIN',
      place: 'SECOND',
      devpostUrl: 'https://devpost.com/software/koff',
    },
    {
      name: 'Third Place',
      winner: 'adiona',
      type: 'MAIN',
      place: 'THIRD',
      devpostUrl: 'https://devpost.com/software/adiona',
    },
    {
      name: 'Best use of Twilio',
      winner: 'adiona',
      type: 'SPONSOR',
      sponsor: 'Twilio',
      devpostUrl: 'https://devpost.com/software/adiona',
    },
    {
      name: 'The Greatest Makers',
      winner: 'Andromeda',
      type: 'SPONSOR',
      sponsor: 'Arcitecta',
      devpostUrl: 'https://devpost.com/software/andromeda',
    },
    {
      name: 'Be Curious',
      winner: 'Andromeda',
      type: 'SPONSOR',
      sponsor: 'Latitude',
      devpostUrl: 'https://devpost.com/software/andromeda',
    },
    {
      name: 'Best User-Centric Hack',
      winner: 'TuteBite',
      type: 'SPONSOR',
      sponsor: 'Medipass',
      devpostUrl: 'https://devpost.com/software/tute-bite',
    },
    {
      name: 'Best IoT Hack',
      winner: 'UrineDoc',
      type: 'SPONSOR',
      sponsor: 'Telstra',
      devpostUrl: 'https://devpost.com/software/urinedoc',
    },
    {
      name: 'Community Prize',
      winner: 'UrineDoc',
      type: 'SPONSOR',
      sponsor: 'Australia Post',
      devpostUrl: 'https://devpost.com/software/urinedoc',
    },
    {
      name: 'Data Analytics Prize',
      winner: 'Swiftly',
      type: 'SPONSOR',
      sponsor: 'PwC',
      devpostUrl: 'https://devpost.com/software/project-lymqria6usj1',
    },
    {
      name: 'Best use of EchoAR',
      winner: 'Swiftly',
      type: 'SPONSOR',
      sponsor: 'echoAR',
      devpostUrl: 'https://devpost.com/software/project-lymqria6usj1',
    },
    {
      name: 'Customer Obsessed',
      winner: 'FoodMatch',
      type: 'SPONSOR',
      sponsor: 'Coles',
      devpostUrl: 'https://devpost.com/software/foodmatch-7ro6nq',
    },
    {
      name: 'Creative Pitch Prize',
      winner: 'Gecko',
      type: 'SPONSOR',
      sponsor: 'PwC',
      devpostUrl: 'https://devpost.com/software/gecko-oeh8sy',
    },
    {
      name: 'Best Design',
      winner: 'Culie',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/culie',
    },
    {
      name: 'Most Creative Idea',
      winner: 'Tiles',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/tiles-ftqcsp',
    },
    {
      name: 'Best Social Impact',
      winner: 'SkyNet',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/skynet-ela2x3',
    },
    {
      name: "People's Choice",
      winner: 'Sense+',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/sense-unl741',
    },
  ],
}
