import type { Event } from './types'

export const event: Event = {
  name: 'UNIHACK 2022',
  year: 2022,
  type: 'VIRTUAL',
  url: 'https://unihack2022.devpost.com/',
  location: 'Remote',
  startDate: new Date('2022-02-25'),
  endDate: new Date('2022-02-27'),
  prizes: [
    {
      name: 'First Place',
      winner: 'DJ PAL',
      type: 'MAIN',
      place: 'FIRST',
      devpostUrl: 'https://devpost.com/software/dj-pal',
    },
    {
      name: 'Second Place',
      winner: 'GreenWays',
      type: 'MAIN',
      place: 'SECOND',
      devpostUrl: 'https://devpost.com/software/greenways-bkytwg',
    },
    {
      name: 'Third Place',
      winner: 'S2T (LSTM)',
      type: 'MAIN',
      place: 'THIRD',
      devpostUrl: 'https://devpost.com/software/s2t',
    },
    {
      name: 'Creative Pitch Prize',
      winner: 'DJ PAL',
      type: 'SPONSOR',
      sponsor: 'PwC',
      devpostUrl: 'https://devpost.com/software/dj-pal',
    },
    {
      name: 'Best Global Social Impact Hack',
      winner: 'GreenWays',
      type: 'SPONSOR',
      sponsor: 'Atlassian',
      devpostUrl: 'https://devpost.com/software/greenways-bkytwg',
    },
    {
      name: 'Most Scalable Prize',
      winner: 'GreenWays',
      type: 'SPONSOR',
      sponsor: 'Bukalapak',
      devpostUrl: 'https://devpost.com/software/greenways-bkytwg',
    },
    {
      name: 'Most Innovative Hack',
      winner: 'GreenWays',
      type: 'SPONSOR',
      sponsor: 'Bosch',
      devpostUrl: 'https://devpost.com/software/greenways-bkytwg',
    },
    {
      name: 'Commit to Greatness Prize',
      winner: 'GreenWays',
      type: 'SPONSOR',
      sponsor: 'Tyro',
      devpostUrl: 'https://devpost.com/software/greenways-bkytwg',
    },
    {
      name: 'The Customer Experience Award',
      winner: 'Food Frog',
      type: 'SPONSOR',
      sponsor: 'Zendesk',
      devpostUrl: 'https://devpost.com/software/unobtainable-magic-tesseract',
    },
    {
      name: 'Food Waste Warrior Prize',
      winner: 'Best Before',
      type: 'SPONSOR',
      sponsor: 'Fresho',
      devpostUrl: 'https://devpost.com/software/best-before-yn83l9',
    },
    {
      name: 'Engineering Excellence Prize',
      winner: 'Qube',
      type: 'SPONSOR',
      sponsor: 'Macquarie',
      devpostUrl: 'https://devpost.com/software/qube',
    },
    {
      name: 'Data Analytics Prize',
      winner: 'MiniMelbourne',
      type: 'SPONSOR',
      sponsor: 'PwC',
      devpostUrl: 'https://devpost.com/software/minimebourne',
    },
    {
      name: 'Best Use of Twilio',
      winner: 'NiteLyte',
      type: 'SPONSOR',
      sponsor: 'Twilio',
      devpostUrl: 'https://devpost.com/software/nitelyte',
    },
    {
      name: 'Best Design',
      winner: 'GreenWays',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/greenways-bkytwg',
    },
    {
      name: 'Most Creative Idea',
      winner: 'Zom-B-Gone',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/zom-b-gone',
    },
    {
      name: 'IG UNIHACK Prize',
      winner: 'DJ PAL',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/dj-pal',
    },
    {
      name: "People's Choice",
      winner: 'S2T (LSTM)',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/s2t',
    },
    {
      name: 'Local Impact Prize',
      winner: 'Crowdmap',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/crowdmap-qmd0ob',
    },
    {
      name: "First Timers' Prize",
      winner: 'Trashy',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/new-leaf-qgxbwh',
    },
    {
      name: 'Most Entertaining Pitch',
      winner: 'Food Frog',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/unobtainable-magic-tesseract',
    },
  ],
}
