import type { Event } from './types'

export const event: Event = {
  name: 'UNIHACK 2023',
  year: 2023,
  type: 'HYBRID',
  url: 'https://unihack2023.devpost.com/',
  location: 'Australia and New Zealand',
  startDate: new Date('2023-03-03'),
  endDate: new Date('2023-03-05'),
  prizes: [
    {
      name: 'First Place',
      winner: 'SMD',
      type: 'MAIN',
      place: 'FIRST',
      devpostUrl: 'https://devpost.com/software/smd',
    },
    {
      name: 'Second Place',
      winner: 'Zentria',
      type: 'MAIN',
      place: 'SECOND',
      devpostUrl: 'https://devpost.com/software/zentria',
    },
    {
      name: 'Third Place',
      winner: 'KONRAN',
      type: 'MAIN',
      place: 'THIRD',
      devpostUrl: 'https://devpost.com/software/konran',
    },
    {
      name: "Creative Data-Driven Pitch Prize",
      winner: 'Foodplan',
      type: 'SPONSOR',
      sponsor: 'PwC',
      devpostUrl: 'https://devpost.com/software/foodplan',
    },
    {
      name: 'Most #Human Prize',
      winner: 'Zentria',
      type: 'SPONSOR',
      sponsor: 'Xero',
      devpostUrl: 'https://devpost.com/software/zentria',
    },
    {
      name: 'Most Healthy Hack',
      winner: 'Zentria',
      type: 'SPONSOR',
      sponsor: 'Miga Health',
      devpostUrl: 'https://devpost.com/software/zentria',
    },
    {
      name: 'Best Design',
      winner: 'Balanced Bites',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/unsw-dream-team',
    },
    {
      name: 'Most Creative Idea',
      winner: 'SMD',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/smd',
    },
    {
      name: 'Social Impact Prize',
      winner: 'SMD',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/smd',
    },
    {
      name: "First Timers' Prize",
      winner: 'catpush',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/catpush',
    },
    {
      name: 'Most Entertaining Pitch',
      winner: 'Beardom',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/beardom',
    },
    {
      name: "People's Choice Award",
      winner: 'VVOL - We Volunteer',
      type: 'CATEGORY',
      devpostUrl: 'https://devpost.com/software/vvol',
    },
  ],
}
