import type { Event } from './types'

export const event: Event = {
  name: 'UNIHACK 2026',
  year: 2026,
  type: 'HYBRID',
  url: 'https://unihack2026.devpost.com/',
  location: 'Australia and New Zealand',
  startDate: new Date('2026-03-13'),
  endDate: new Date('2026-03-15'),
  prizes: [
    {
      name: 'First Place',
      type: 'MAIN',
      place: 'FIRST',
      winner: 'ANTRUM MK 1',
      devpostUrl: 'https://devpost.com/software/antrum-mk-1',
      university: 'Monash',
    },
    {
      name: 'Second Place',
      winner: 'Sentinel AI',
      type: 'MAIN',
      place: 'SECOND',
      devpostUrl: 'https://devpost.com/software/sentinel-ai-rzp29l',
      university: 'Monash',
    },
    {
      name: 'Third Place',
      winner: 'Cowdar',
      type: 'MAIN',
      place: 'THIRD',
      devpostUrl: 'https://devpost.com/software/cowdar',
      university: 'Monash',
    },
    {
      name: 'The EU Shared Future Prize',
      type: 'SPONSOR',
      sponsor: 'European Union',
      winner: 'Anchor',
      devpostUrl: 'https://unihack2026.devpost.com/submissions/967079-anchor',
      university: 'Monash',
    },
    {
      name: 'First Timers Prize',
      type: 'SPONSOR',
      sponsor: 'Atlassian',
      winner: 'StepFlow',
      devpostUrl: 'https://unihack2026.devpost.com/submissions/969518-stepflow',
      university: 'Monash',
    },
    {
      name: 'Best Use of Elastic Technology',
      type: 'SPONSOR',
      sponsor: 'Elastic',
      winner: 'Hooked',
      devpostUrl: 'https://unihack2026.devpost.com/submissions/969724-hooked',
      university: 'UTS',
    },
    {
      name: 'AI Solutions Prize',
      type: 'SPONSOR',
      sponsor: 'Quantium',
      winner: 'Safe Trace',
      devpostUrl: 'https://unihack2026.devpost.com/submissions/969368-safe-trace',
      university: 'UQ/Monash',
    },
    {
      name: 'Best Design',
      type: 'CATEGORY',
      winner: 'Echo',
      devpostUrl: 'https://devpost.com/software/echo-107u6c',
      university: 'UNSW/USYD',
    },
    {
      name: 'Most Creative Idea',
      type: 'CATEGORY',
      winner: 'Tracksync',
      devpostUrl: 'https://devpost.com/software/tracksync',
      university: 'UNSW',
    },
    {
      name: 'Social Impact Prize',
      type: 'CATEGORY',
      winner: 'MeshMap',
      devpostUrl: 'https://devpost.com/software/meshnet',
      university: 'UNSW',
    },
    {
      name: 'Most Fun Idea',
      type: 'CATEGORY',
      winner: 'Peersuade',
      devpostUrl: 'https://devpost.com/software/peersuade',
      university: 'UNSW',
    },
    {
      name: "People's Choice",
      type: 'CATEGORY',
      winner: 'UniAid',
      devpostUrl: 'https://devpost.com/software/uniaid-tvojlk',
      university: 'Monash',
    },
    {
      name: 'Most Entertaining Pitch',
      type: 'CATEGORY',
      winner: 'ToiletGO',
      devpostUrl: 'https://devpost.com/software/orion-15qdnf',
      university: 'Monash/UniMelb',
    },
  ],
}
